ALTER TABLE budgets
ADD COLUMN is_fixed BOOLEAN DEFAULT FALSE,
ADD COLUMN is_flexible BOOLEAN DEFAULT FALSE,
ADD COLUMN min_amount DECIMAL(10,2) DEFAULT 0,
ADD COLUMN max_amount DECIMAL(10,2) DEFAULT 0,
ADD COLUMN progress DECIMAL(5,2) DEFAULT 0; 